<?php
/**
 * GENERATED by scripts/generate-catalogue.mjs from src/content/products.ts (runs in postbuild).
 * Do not edit by hand. The website's product groups, used by the admin product editor.
 */
return [
    ['id' => '01', 'name' => 'Water Cooler spare parts', 'slug' => 'water-cooler-spare-parts'],
    ['id' => '02', 'name' => 'Deep freezer & Display counter Parts', 'slug' => 'deep-freezer-display-counter-parts'],
    ['id' => '03', 'name' => 'Commercial Kitchen Spare parts', 'slug' => 'commercial-kitchen-spare-parts'],
    ['id' => '04', 'name' => 'Caster wheel', 'slug' => 'caster-wheel'],
    ['id' => '05', 'name' => 'On demand Customized Products', 'slug' => 'on-demand-customized-products'],
];
