/**
 * S8 · PanIndiaMap — §13 (rebuilt in Round 2, ask 13)
 * bg: --surface-alt
 *
 * An accurate dot-matrix world map (Natural Earth 1:10m, India point-of-view edition,
 * generated by scripts/gen-world-dots.mjs into worldDots.ts). India is drawn with the
 * Government of India depiction — Jammu & Kashmir and Ladakh complete, nothing cut at
 * the top — in burgundy; the rest of the world is a muted silver-grey dot backdrop.
 * Chandigarh is the pulsing origin. Arcs are UNLABELLED: dense inside India (the Pan
 * Bharat delivery network, today), and a few longer, lighter arcs fanning across the
 * world to carry the *ambition* ("Crafted in Bharat, made for the world.").
 *
 * HONESTY (§19): no export or country claims, no country / city names, no flags. The
 * world arcs are illustrative direction, and the caption says so. See ADR-012.
 *
 * Motion (once, on scroll-in): outline draws, India dots settle, domestic arcs draw, a
 * light dot travels each arc once, then the world arcs fan out. transform / opacity /
 * stroke-dashoffset only. Reduced motion: the finished map, no pulse.
 */

'use client';

import { useRef } from 'react';
import { useGSAP } from '@gsap/react';
import { gsap, ScrollTrigger, DURATIONS, EASINGS } from '@/lib/motion';
import { useMaskRise } from '@/hooks/useMotion';
import { site } from '@/content/site';
import {
  WORLD_W, WORLD_H, WORLD_DOTS, INDIA_DOTS, INDIA_OUTLINE,
  STEP_WORLD_U, STEP_INDIA_U, project,
} from './worldDots';

gsap.registerPlugin(ScrollTrigger);

const ORIGIN = project(76.78, 30.73); // Chandigarh (verified base)

/* Regional points inside India — generic, unlabelled (no cities claimed). */
const DOMESTIC: [number, number][] = [
  [73.5, 23.5], [75.5, 15.5], [77.6, 11.8], [80.2, 13.4], [79.0, 21.0], [82.5, 17.5],
  [85.8, 20.5], [88.3, 22.6], [91.7, 26.2], [94.2, 25.6], [84.5, 25.6], [78.2, 26.8],
  [74.2, 27.2], [70.8, 22.6], [76.4, 9.6], [81.2, 23.6],
];
/* Broad world points — illustrative direction only (the ambition), no names. */
const WORLD: [number, number][] = [
  [10, 50], [12, 30], [37, -2], [47, 25], [101, 14], [117, 34], [134, -25], [-58, -15], [-80, 38],
];

const round = (n: number) => Math.round(n * 10) / 10;

function arcPath(to: { x: number; y: number }, lift: number) {
  const mx = (ORIGIN.x + to.x) / 2;
  const my = (ORIGIN.y + to.y) / 2;
  const dist = Math.hypot(to.x - ORIGIN.x, to.y - ORIGIN.y);
  const cy = my - Math.min(dist * lift, 190);
  return `M${round(ORIGIN.x)} ${round(ORIGIN.y)}Q${round(mx)} ${round(cy)} ${round(to.x)} ${round(to.y)}`;
}

const domestic = DOMESTIC.map(([lo, la]) => {
  const p = project(lo, la);
  return { p, d: arcPath(p, 0.28) };
});
const world = WORLD.map(([lo, la]) => {
  const p = project(lo, la);
  return { p, d: arcPath(p, 0.3) };
});

const CSS = `
.pim { position: relative; background: var(--surface-alt); padding: calc(var(--section-y) + 16px) var(--grid-page-padding) calc(var(--section-y) + 24px); overflow: hidden; }
.pim-inner { max-width: calc(var(--grid-max) + 2 * var(--grid-page-padding)); margin: 0 auto; }
.pim-head { display: grid; grid-template-columns: minmax(0, 1fr); gap: var(--space-md); align-items: end; }
.pim-label { display: flex; align-items: center; gap: 10px; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.16em; color: var(--muted); font-weight: 600; font-family: var(--font-archivo); margin-bottom: var(--space-sm); }
.pim-label i { width: 24px; height: 2px; background: var(--burgundy); display: inline-block; }
.pim-h2 { font-family: var(--font-archivo); font-variation-settings: "wdth" 125; font-size: clamp(1.75rem, 3.5vw, 2.75rem); font-weight: 650; line-height: 1.1; letter-spacing: -0.025em; color: var(--ink); max-width: 20ch; text-wrap: balance; margin-bottom: var(--space-md); }
.pim-lead { font-size: 1.0625rem; line-height: 1.65; color: var(--body); max-width: 52ch; }
.pim-legend { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: var(--space-sm); }
.pim-legend li { display: flex; align-items: center; gap: var(--space-sm); font-size: 0.9375rem; color: var(--ink); font-weight: 500; line-height: 1.35; }
.pim-legend svg { flex: none; }
.pim-frame { position: relative; margin-top: var(--space-xl); overflow: hidden; border-top: 1px solid var(--grey-warm); border-bottom: 1px solid var(--grey-warm); background: linear-gradient(180deg, rgba(255,255,255,.7), transparent 55%); }
.pim-svg { display: block; width: 230%; height: auto; margin-left: -115.6%; }
.pim-reg { position: absolute; width: 9px; height: 9px; border: solid var(--grey-warm); }
.pim-reg.tl { top: 8px; left: 8px; border-width: 1px 0 0 1px; } .pim-reg.tr { top: 8px; right: 8px; border-width: 1px 1px 0 0; }
.pim-reg.bl { bottom: 8px; left: 8px; border-width: 0 0 1px 1px; } .pim-reg.br { bottom: 8px; right: 8px; border-width: 0 1px 1px 0; }
.pim-foot { display: grid; grid-template-columns: minmax(0, 1fr); gap: var(--space-md); margin-top: var(--space-lg); align-items: end; }
.pim-tag-dev { font-family: var(--font-devanagari), sans-serif; font-weight: 600; font-size: clamp(1.5rem, 3.2vw, 2.5rem); line-height: 1.5; }
.pim-tag-en { font-size: clamp(1rem, 1.6vw, 1.25rem); color: var(--body); margin-top: 2px; }
.pim-note { font-size: 0.75rem; line-height: 1.5; color: var(--muted); max-width: 46ch; }
.pim-ring { transform-box: fill-box; transform-origin: center; opacity: 0; }
@media (prefers-reduced-motion: no-preference) {
  .pim-ring { animation: pim-pulse 3s cubic-bezier(.16,1,.3,1) infinite; }
  .pim-ring.b { animation-delay: 1.5s; }
}
@keyframes pim-pulse { 0% { transform: scale(.4); opacity: .7; } 70%, 100% { transform: scale(1); opacity: 0; } }
@media (min-width: 720px) {
  .pim-svg { width: 100%; margin-left: 0; }
}
@media (min-width: 900px) {
  .pim-head { grid-template-columns: minmax(0, 7fr) minmax(0, 5fr); gap: var(--space-xl); }
  .pim-foot { grid-template-columns: minmax(0, 1fr) minmax(0, auto); }
}
`;

export default function PanIndiaMap() {
  const sectionRef = useRef<HTMLElement>(null);
  const headingRef = useRef<HTMLHeadingElement>(null);
  useMaskRise(headingRef);

  useGSAP(() => {
    const root = sectionRef.current;
    if (!root) return;
    const mm = gsap.matchMedia();
    mm.add('(prefers-reduced-motion: no-preference)', () => {
      const q = <T extends Element>(s: string) => gsap.utils.toArray<T>(s, root);
      const outline = root.querySelector<SVGPathElement>('.pim-outline');
      const worldDots = root.querySelector('.pim-world-dots');
      const indiaDots = root.querySelector('.pim-india-dots');
      const dArcs = q<SVGPathElement>('.pim-arc-d');
      const wArcs = q<SVGPathElement>('.pim-arc-w');
      const ends = q<SVGElement>('.pim-end');
      const lights = q<SVGCircleElement>('.pim-light');
      const origin = q<SVGElement>('.pim-origin');
      if (!outline || !worldDots || !indiaDots) return;

      gsap.set(worldDots, { opacity: 0 });
      gsap.set(indiaDots, { opacity: 0 });
      gsap.set(outline, { strokeDasharray: 1, strokeDashoffset: 1, fillOpacity: 0 });
      gsap.set([...dArcs, ...wArcs], { strokeDasharray: 1, strokeDashoffset: 1 });
      gsap.set(ends, { opacity: 0 });
      gsap.set(lights, { opacity: 0 });
      gsap.set(origin, { opacity: 0 });

      /* light dot rides an arc once: transform only */
      const ride = (arc: SVGPathElement, light: SVGCircleElement, at: number, dur: number, tl: gsap.core.Timeline) => {
        const len = arc.getTotalLength();
        const o = { p: 0 };
        tl.set(light, { opacity: 1 }, at);
        tl.to(o, {
          p: 1, duration: dur, ease: EASINGS.powerInOut,
          onUpdate: () => {
            const pt = arc.getPointAtLength(o.p * len);
            gsap.set(light, { x: pt.x, y: pt.y });
          },
        }, at);
        tl.to(light, { opacity: 0, duration: DURATIONS.micro }, at + dur);
      };

      const tl = gsap.timeline({
        scrollTrigger: { trigger: root.querySelector('.pim-frame'), start: 'top 72%', once: true },
      });
      tl.to(worldDots, { opacity: 1, duration: DURATIONS.full, ease: EASINGS.out }, 0)
        .to(outline, { strokeDashoffset: 0, duration: DURATIONS.full, ease: EASINGS.inOut }, 0.2)
        .to(outline, { fillOpacity: 0.05, duration: DURATIONS.long, ease: EASINGS.out }, 0.9)
        .to(indiaDots, { opacity: 1, duration: DURATIONS.long, ease: EASINGS.out }, 0.7)
        .to(origin, { opacity: 1, duration: DURATIONS.short, ease: EASINGS.out }, 1.0);
      dArcs.forEach((arc, i) => {
        const at = 1.2 + i * 0.07;
        tl.to(arc, { strokeDashoffset: 0, duration: DURATIONS.medium, ease: EASINGS.powerInOut }, at);
        tl.to(ends[i], { opacity: 1, duration: DURATIONS.short }, at + DURATIONS.medium);
        if (lights[i]) ride(arc, lights[i], at + DURATIONS.medium, DURATIONS.long, tl);
      });
      const wStart = 1.2 + dArcs.length * 0.07 + 0.5;
      wArcs.forEach((arc, i) => {
        const at = wStart + i * 0.14;
        const k = dArcs.length + i;
        tl.to(arc, { strokeDashoffset: 0, duration: DURATIONS.full, ease: EASINGS.inOut }, at);
        tl.to(ends[k], { opacity: 1, duration: DURATIONS.short }, at + DURATIONS.full);
        if (lights[k]) ride(arc, lights[k], at + DURATIONS.full, DURATIONS.full, tl);
      });

      return () => {
        tl.scrollTrigger?.kill();
        tl.kill();
        gsap.set([worldDots, indiaDots, outline, ...dArcs, ...wArcs, ...ends, ...lights, ...origin], { clearProps: 'all' });
      };
    });
    return () => mm.revert();
  }, { scope: sectionRef });

  return (
    <section ref={sectionRef} className="pim" aria-labelledby="map-heading">
      <style>{CSS}</style>
      <div className="pim-inner">
        <div className="pim-head">
          <div>
            <div className="pim-label"><i aria-hidden="true" />Pan Bharat</div>
            <h2 id="map-heading" ref={headingRef} className="pim-h2">From Chandigarh to every corner of India.</h2>
            {/* COPY: drafted from verified facts (§5.10; Chandigarh base; Pan Bharat delivery network) — needs client approval */}
            <p className="pim-lead">
              From a single component to thousands of parts for a production line, we manufacture for businesses that build.
              Dispatch is from {site.contact.city} through our Pan Bharat delivery network.
            </p>
          </div>
          <ul className="pim-legend">
            <li>
              <svg width="22" height="22" viewBox="0 0 22 22" aria-hidden="true">
                <circle cx="11" cy="11" r="9" fill="none" stroke="var(--burgundy)" strokeWidth="1" opacity="0.4" />
                <circle cx="11" cy="11" r="5" fill="var(--burgundy)" />
              </svg>
              Origin: {site.contact.city}
            </li>
            <li>
              <svg width="22" height="22" viewBox="0 0 22 22" aria-hidden="true">
                <path d="M2 17Q11 2 20 6" fill="none" stroke="var(--burgundy)" strokeWidth="1.5" />
              </svg>
              Pan Bharat delivery network, today
            </li>
            <li>
              <svg width="22" height="22" viewBox="0 0 22 22" aria-hidden="true">
                <path d="M2 17Q11 2 20 6" fill="none" stroke="var(--grey-metal)" strokeWidth="1" />
              </svg>
              The ambition: a globally recognised Indian manufacturing brand
            </li>
          </ul>
        </div>

        <figure style={{ margin: 0 }}>
          <div className="pim-frame">
            <svg
              className="pim-svg"
              viewBox={`0 0 ${WORLD_W} ${WORLD_H}`}
              fill="none"
              role="img"
              aria-label="Dot-matrix world map with India highlighted in burgundy. Chandigarh is the origin of the Pan Bharat delivery network; the lighter arcs are illustrative and show ambition, not delivery destinations."
            >
              {/* world backdrop: muted dots */}
              <path className="pim-world-dots" d={WORLD_DOTS} stroke="var(--silver)" strokeOpacity="0.6" strokeWidth="3.4" strokeLinecap="round" strokeDasharray={`0 ${STEP_WORLD_U}`} />
              {/* India: Government of India depiction */}
              <path className="pim-outline" d={INDIA_OUTLINE} pathLength={1} fill="var(--burgundy)" fillOpacity="0.05" stroke="var(--burgundy)" strokeWidth="1.4" strokeLinejoin="round" />
              <path className="pim-india-dots" d={INDIA_DOTS} stroke="var(--burgundy)" strokeOpacity="0.8" strokeWidth="1.35" strokeLinecap="round" strokeDasharray={`0 ${STEP_INDIA_U}`} />

              {/* arcs: dense inside India, longer and lighter across the world */}
              {world.map((a, i) => (
                <path key={`w${i}`} className="pim-arc-w" d={a.d} pathLength={1} stroke="var(--grey-metal)" strokeOpacity="0.7" strokeWidth="1.1" strokeLinecap="round" />
              ))}
              {domestic.map((a, i) => (
                <path key={`d${i}`} className="pim-arc-d" d={a.d} pathLength={1} stroke="var(--burgundy)" strokeOpacity="0.8" strokeWidth="1.2" strokeLinecap="round" />
              ))}
              {[...domestic, ...world].map((a, i) => (
                <circle key={`e${i}`} className="pim-end" cx={a.p.x} cy={a.p.y} r={i < domestic.length ? 2.1 : 2.4} fill="var(--surface)" stroke={i < domestic.length ? 'var(--burgundy)' : 'var(--grey-metal)'} strokeWidth="1.1" />
              ))}
              {[...domestic, ...world].map((_, i) => (
                <circle key={`l${i}`} className="pim-light" r="2.2" fill={i < domestic.length ? 'var(--burgundy-bright)' : 'var(--grey-metal)'} />
              ))}

              {/* origin: Chandigarh */}
              <g className="pim-origin">
                <circle className="pim-ring" cx={ORIGIN.x} cy={ORIGIN.y} r="20" stroke="var(--burgundy)" strokeWidth="1.2" />
                <circle className="pim-ring b" cx={ORIGIN.x} cy={ORIGIN.y} r="20" stroke="var(--burgundy)" strokeWidth="1.2" />
                <circle cx={ORIGIN.x} cy={ORIGIN.y} r="5" fill="var(--burgundy)" stroke="var(--surface)" strokeWidth="1.5" />
              </g>
            </svg>
            <span className="pim-reg tl" aria-hidden="true" /><span className="pim-reg tr" aria-hidden="true" />
            <span className="pim-reg bl" aria-hidden="true" /><span className="pim-reg br" aria-hidden="true" />
          </div>

          <figcaption className="pim-foot">
            <div>
              <p lang="sa" className="pim-tag-dev">
                <span style={{ color: 'var(--burgundy)' }}>भारते शिल्पितम्, </span>
                <span style={{ color: 'var(--grey-metal)' }}>विश्वय निर्मितम्</span>
              </p>
              <p lang="en" className="pim-tag-en">{site.tagline.english}</p>
            </div>
            <p className="pim-note">Illustrative. Arcs show direction of travel, not delivery destinations.</p>
          </figcaption>
        </figure>
      </div>
    </section>
  );
}
