/**
 * S8 · PanIndiaMap — §13 (rebuilt in Round 2, ask 13)
 * bg: --surface-alt
 *
 * An accurate dot-matrix world map (Natural Earth 1:10m, India point-of-view edition,
 * generated by scripts/gen-world-dots.mjs into worldDots.ts). India is drawn with the
 * Government of India depiction — Jammu & Kashmir and Ladakh complete, nothing cut at
 * the top — in mould-steel blue (--map-land); the rest of the world is a muted steel-grey dot backdrop.
 * Colour story, "molten to cooled": Chandigarh is the pulsing resin-amber origin, domestic arcs cool from
 * amber into burgundy, and each arc ends on a badge carrying one of the brand's own part pictograms.
 * Legend rows (hover / focus / click) highlight the matching layer; they repeat the legend wording only.
 * Arcs are UNLABELLED: dense inside India (the Pan
 * Bharat delivery network, today), and a few longer, lighter arcs fanning across the
 * world to carry the *ambition* ("Crafted in Bharat, made for the world.").
 *
 * Below the map: "beyond the catalogue" — custom parts made to a sample, drawing or photo,
 * many industries, repeat orders across India. The old catalogue unit chart and the
 * part-symbol badges were removed (client brief): the catalogue is not the limit of the work.
 *
 * HONESTY (§19): no export or country claims, no country / city names, no flags, no capacity
 * figures. The world arcs are illustrative direction, and the caption says so. See ADR-012.
 *
 * Motion (once, on scroll-in): outline draws, India dots settle, domestic arcs draw, a
 * light dot travels each arc once, then the world arcs fan out. transform / opacity /
 * stroke-dashoffset only. Reduced motion: the finished map, no pulse.
 */

'use client';

import Highlight from '@/components/ui/Highlight';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useGSAP } from '@gsap/react';
import { gsap, ScrollTrigger, DURATIONS, EASINGS } from '@/lib/motion';
import { useMaskRise } from '@/hooks/useMotion';
import { site } from '@/content/site';
import { pictogramPaths, type PictogramName } from '@/components/brand/Pictogram';
import { ArrowUpRight } from '@phosphor-icons/react/dist/ssr/ArrowUpRight';
import {
  WORLD_DOTS, INDIA_DOTS, INDIA_OUTLINE, INDIA_ISLANDS,
  STEP_WORLD_U, STEP_INDIA_U, INDIA_SCALE, INDIA_CLON, INDIA_CLAT, project,
} from './worldDots';

gsap.registerPlugin(ScrollTrigger);

/* Two-layer composition: a wide dotted world band behind (Africa, Europe, Asia, Australia, the
   Americas as a faint far edge), India enlarged in front by INDIA_SCALE about its centre. Points
   inside India go through `ind()`, world points through plain `project()`. */
const ind = (lon: number, lat: number) => {
  const c = project(INDIA_CLON, INDIA_CLAT);
  const p = project(lon, lat);
  return { x: c.x + (p.x - c.x) * INDIA_SCALE, y: c.y + (p.y - c.y) * INDIA_SCALE };
};
const ORIGIN = ind(76.78, 30.73); // Chandigarh (verified base)
const IND_T = `translate(${project(INDIA_CLON, INDIA_CLAT).x} ${project(INDIA_CLON, INDIA_CLAT).y}) scale(${INDIA_SCALE}) translate(${-project(INDIA_CLON, INDIA_CLAT).x} ${-project(INDIA_CLON, INDIA_CLAT).y})`;

/* Regional points inside India — generic, unlabelled (no cities claimed). */
const DOMESTIC: [number, number][] = [
  [73.5, 23.5], [75.5, 15.5], [77.6, 11.8], [80.2, 13.4], [79.0, 21.0], [82.5, 17.5],
  [85.8, 20.5], [88.3, 22.6], [91.7, 26.2], [94.2, 25.6], [84.5, 25.6], [78.2, 26.8],
  [74.2, 27.2], [70.8, 22.6], [76.4, 9.6], [81.2, 23.6],
];
/* Broad world points — illustrative direction only (the ambition), no names. They sit out
   in the other continents so every one of these arcs visibly leaves India's border. */
const WORLD: [number, number][] = [
  [8, 48], [-8, 8], [26, -22], [46, 28], [122, 14], [122, 38], [140, 36], [134, -26], [-40, -12], [18, 18],
];

const VB = { x: 0, y: 30, w: 1075, h: 505 };
const inFrame = (p: { x: number; y: number }) =>
  p.x > VB.x + 8 && p.x < VB.x + VB.w - 8 && p.y > VB.y + 8 && p.y < VB.y + VB.h - 8;

const round = (n: number) => Math.round(n * 10) / 10;

/* Faint lat/long graticule (plate carree, so straight lines): drawn behind the dots only. */
const GRATICULE = (() => {
  const d: string[] = [];
  for (let lon = -30; lon <= 160; lon += 30) {
    d.push(`M${round(project(lon, 0).x)} ${VB.y}V${VB.y + VB.h}`);
  }
  for (let lat = 60; lat >= -30; lat -= 30) {
    d.push(`M${VB.x} ${round(project(0, lat).y)}H${VB.x + VB.w}`);
  }
  return d.join('');
})();

type Layer = 'origin' | 'domestic' | 'world';
const LEGEND: { layer: Layer; text: string }[] = [
  { layer: 'origin', text: `Origin: ${site.contact.city}` },
  { layer: 'domestic', text: 'Pan Bharat delivery network, today' },
  { layer: 'world', text: 'The ambition: a globally recognised Indian manufacturing brand' },
];

function arcPath(to: { x: number; y: number }, lift: number) {
  const mx = (ORIGIN.x + to.x) / 2;
  const my = (ORIGIN.y + to.y) / 2;
  const dist = Math.hypot(to.x - ORIGIN.x, to.y - ORIGIN.y);
  const cy = my - Math.min(dist * lift, 130);
  return `M${round(ORIGIN.x)} ${round(ORIGIN.y)}Q${round(mx)} ${round(cy)} ${round(to.x)} ${round(to.y)}`;
}

/* The brand's own part drawings (water-cooler parts), cycled over the domestic end badges. They are
   decoration for "what moves through the network", unlabelled: no product, place or volume claim. */
const GLYPHS: PictogramName[] = [
  'float-valve', 'push-cock', 'hinge', 'door-lock', 'f-bush',
  'connecting-bush', 'waste-pipe', 'ventilation-jalli', 'adjustable-leg-insert', 'gasket',
];
const BADGE_R = 10.5;
const GLYPH = 14; // glyph box in svg units, drawn on the pictogram's 48 grid

const domestic = DOMESTIC.map(([lo, la], i) => {
  const p = ind(lo, la);
  return { p, d: arcPath(p, 0.28), glyph: GLYPHS[i % GLYPHS.length] };
});
const world = WORLD.map(([lo, la]) => {
  const p = project(lo, la);
  return { p, d: arcPath(p, 0.26) };
});

const CSS = `
.pim { position: relative; background: var(--surface-alt); padding: calc(var(--section-y) + 16px) var(--grid-page-padding) calc(var(--section-y) + 24px); overflow: hidden; }
.pim-inner { max-width: calc(var(--grid-max) + 2 * var(--grid-page-padding)); margin: 0 auto; }
.pim-head { display: grid; grid-template-columns: minmax(0, 1fr); gap: var(--space-md); align-items: end; }
.pim-label { display: flex; align-items: center; gap: 10px; font-size: var(--fs-label); text-transform: uppercase; letter-spacing: var(--tr-label); color: var(--muted); font-weight: 600; font-family: var(--font-archivo), sans-serif; margin-bottom: var(--space-sm); line-height: var(--lh-label); }
.pim-h2 { font-family: var(--font-archivo); font-variation-settings: "wdth" 125; font-size: var(--fs-h2); font-weight: 650; line-height: var(--lh-h2); letter-spacing: var(--tr-h2); color: var(--ink); max-width: 20ch; text-wrap: balance; margin-bottom: var(--space-md); }
.pim-lead { font-size: 1.0625rem; line-height: 1.65; color: var(--body); max-width: 52ch; }
.pim-legend { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: var(--space-sm); }
.pim-legend li { display: block; }
.pim-legend button { display: flex; align-items: center; gap: var(--space-sm); width: 100%; min-height: 44px; margin: 0; padding: 0; background: none; border: 0; border-radius: var(--radius-card); font: inherit; font-size: 0.9375rem; color: var(--ink); font-weight: 500; line-height: 1.35; text-align: left; cursor: pointer; }
.pim-legend button:hover, .pim-legend button[aria-pressed="true"] { color: var(--burgundy); }
.pim-legend button[aria-pressed="true"] span { text-decoration: underline; text-decoration-thickness: 1px; text-underline-offset: 4px; }
.pim-legend button:focus-visible { outline: 2px solid var(--burgundy); outline-offset: 4px; }
.pim-legend svg { flex: none; }
.pim-frame { position: relative; margin-top: var(--space-xl); overflow: hidden; border-top: 1px solid var(--grey-warm); border-bottom: 1px solid var(--grey-warm); background: linear-gradient(180deg, rgba(255,255,255,.7), transparent 55%); }
.pim-stage { overflow: hidden; -webkit-mask-image: linear-gradient(to right, transparent, var(--ink) 9%, var(--ink) 91%, transparent), linear-gradient(to bottom, transparent, var(--ink) 7%, var(--ink) 93%, transparent); -webkit-mask-composite: source-in; mask-image: linear-gradient(to right, transparent, var(--ink) 9%, var(--ink) 91%, transparent), linear-gradient(to bottom, transparent, var(--ink) 7%, var(--ink) 93%, transparent); mask-composite: intersect; }
.pim-svg { display: block; width: 175%; height: auto; margin-left: -55%; }
.pim-reg { position: absolute; width: 9px; height: 9px; border: solid var(--grey-warm); }
.pim-reg.tl { top: 8px; left: 8px; border-width: 1px 0 0 1px; } .pim-reg.tr { top: 8px; right: 8px; border-width: 1px 1px 0 0; }
.pim-reg.bl { bottom: 8px; left: 8px; border-width: 0 0 1px 1px; } .pim-reg.br { bottom: 8px; right: 8px; border-width: 0 1px 1px 0; }
.pim-foot { margin-top: var(--space-md); }
.pim-note { font-size: 0.75rem; line-height: 1.5; color: var(--muted); max-width: 46ch; }
.pim-ring { transform-box: fill-box; transform-origin: center; opacity: 0; }
.pim-hit { fill: none; stroke: transparent; stroke-width: 12; pointer-events: stroke; }
.pim-dot { transform-box: fill-box; transform-origin: center; }
/* layer highlight: the matching group comes forward, the rest recede (state set from the legend or an arc) */
.pim[data-hl="domestic"] .pim-g-world, .pim[data-hl="world"] .pim-g-domestic { opacity: 0.14; }
.pim[data-hl="origin"] .pim-g-domestic, .pim[data-hl="origin"] .pim-g-world { opacity: 0.3; }
.pim[data-hl="domestic"] .pim-arc-d, .pim[data-hl="world"] .pim-arc-w { stroke-opacity: 1; stroke-width: 1.9; }
.pim[data-hl="origin"] .pim-dot { transform: scale(1.5); }
@media (prefers-reduced-motion: no-preference) {
  .pim-g { transition: opacity 240ms cubic-bezier(.16,1,.3,1); }
  .pim-arc-d, .pim-arc-w { transition: stroke-width 240ms cubic-bezier(.16,1,.3,1), stroke-opacity 240ms cubic-bezier(.16,1,.3,1); }
  .pim-dot { transition: transform 240ms cubic-bezier(.16,1,.3,1); }
}
@media (prefers-reduced-motion: no-preference) {
  .pim.live .pim-ring { animation: pim-pulse 3s cubic-bezier(.16,1,.3,1) infinite; }
  .pim.live .pim-ring.b { animation-delay: 1.5s; }
}
@keyframes pim-pulse { 0% { transform: scale(.4); opacity: .7; } 70%, 100% { transform: scale(1); opacity: 0; } }

/* Beyond the catalogue: three typographic columns under the map */
.pim-bey { margin-top: var(--space-xl); display: grid; gap: var(--space-lg); }
.pim-bey-h { font-family: var(--font-archivo); font-variation-settings: "wdth" 125; font-size: var(--fs-h3); font-weight: 650; letter-spacing: var(--tr-h3); line-height: var(--lh-h3); color: var(--ink); margin: 0; max-width: 22ch; text-wrap: balance; }
.pim-bey-sub { font-size: 0.9375rem; line-height: 1.6; color: var(--body); margin: var(--space-sm) 0 0; max-width: 40ch; }
.pim-bey-cols { list-style: none; margin: 0; padding: 0; display: grid; gap: var(--space-md); }
.pim-bey-col { position: relative; padding-top: var(--space-sm); border-top: 1px solid var(--grey-warm); }
.pim-bey-col::before { content: ""; position: absolute; left: 0; top: -1px; width: 40px; height: 3px; background: var(--burgundy); }
.pim-bey-k { font-size: var(--fs-label); line-height: var(--lh-label); letter-spacing: var(--tr-label); text-transform: uppercase; font-weight: 600; color: var(--burgundy); font-family: var(--font-archivo), sans-serif; }
.pim-bey-t { margin: var(--space-xs) 0 0; font-family: var(--font-archivo); font-variation-settings: "wdth" 125; font-size: var(--fs-lead-lg); line-height: var(--lh-lead-lg); letter-spacing: var(--tr-lead-lg); font-weight: 600; color: var(--ink); text-wrap: balance; }
.pim-bey-p { margin: var(--space-xs) 0 0; font-size: 0.9375rem; line-height: 1.6; color: var(--body); max-width: 36ch; }
.pim-bey-cta { display: flex; flex-wrap: wrap; gap: var(--space-sm) var(--space-md); margin-top: var(--space-md); }
.pim-go { display: inline-flex; align-items: center; gap: var(--space-xs); min-height: 44px; font-weight: 600; font-size: 0.9375rem; color: var(--burgundy); border-bottom: 2px solid var(--burgundy); text-decoration: none; }
.pim-go svg { transition: transform 200ms cubic-bezier(.16,1,.3,1); }
.pim-go:hover svg { transform: translate3d(2px, -2px, 0); }
.pim-go:focus-visible { outline: 2px solid var(--burgundy); outline-offset: 4px; }
@media (prefers-reduced-motion: reduce) { .pim-go svg { transition: none; } }
@media (min-width: 900px) {
  .pim-bey { grid-template-columns: minmax(0, 4fr) minmax(0, 8fr); gap: var(--space-xl); align-items: start; }
  .pim-bey-cols { grid-template-columns: repeat(3, minmax(0, 1fr)); gap: var(--space-md); }
}
@media (min-width: 720px) {
  .pim-svg { width: 100%; margin-left: 0; }
}
@media (min-width: 900px) {
  .pim-head { grid-template-columns: minmax(0, 7fr) minmax(0, 5fr); gap: var(--space-xl); }
}
`;

export default function PanIndiaMap() {
  const sectionRef = useRef<HTMLElement>(null);
  const headingRef = useRef<HTMLHeadingElement>(null);
  useMaskRise(headingRef);

  /* Layer highlight: hover / focus peeks, click pins. Progressive enhancement: the finished map is
     fully visible with no interaction, and every legend row is a real button. */
  const [pin, setPin] = useState<Layer | null>(null);
  const [peek, setPeek] = useState<Layer | null>(null);
  const hl = peek ?? pin;
  const hover = (layer: Layer) => ({ onPointerEnter: () => setPeek(layer), onPointerLeave: () => setPeek(null) });

  /* looping pulse runs only while the section is on screen */
  useEffect(() => {
    const el = sectionRef.current;
    if (!el || typeof IntersectionObserver === 'undefined') return;
    const io = new IntersectionObserver(([e]) => el.classList.toggle('live', e.isIntersecting), { rootMargin: '80px' });
    io.observe(el);
    return () => io.disconnect();
  }, []);

  useGSAP(() => {
    const root = sectionRef.current;
    if (!root) return;
    const mm = gsap.matchMedia();
    mm.add('(prefers-reduced-motion: no-preference)', () => {
      const q = <T extends Element>(s: string) => gsap.utils.toArray<T>(s, root);
      const outline = root.querySelector<SVGPathElement>('.pim-outline');
      const worldDots = root.querySelector('.pim-world-dots');
      const indiaDots = root.querySelector('.pim-india-dots');
      const islands = root.querySelector('.pim-islands');
      const dArcs = q<SVGPathElement>('.pim-arc-d');
      const wArcs = q<SVGPathElement>('.pim-arc-w');
      const ends = q<SVGElement>('.pim-end');
      const lights = q<SVGCircleElement>('.pim-light');
      const origin = q<SVGElement>('.pim-origin');
      if (!outline || !worldDots || !indiaDots) return;

      gsap.set(worldDots, { opacity: 0 });
      gsap.set([indiaDots, islands], { opacity: 0 });
      gsap.set(outline, { strokeDasharray: 1, strokeDashoffset: 1, fillOpacity: 0 });
      gsap.set([...dArcs, ...wArcs], { strokeDasharray: 1, strokeDashoffset: 1 });
      gsap.set(ends, { opacity: 0 });
      gsap.set(lights, { opacity: 0 });
      gsap.set(origin, { opacity: 0 });

      /* light dot rides an arc once: transform only */
      const ride = (arc: SVGPathElement, light: SVGCircleElement, at: number, dur: number, tl: gsap.core.Timeline) => {
        const len = arc.getTotalLength();
        const o = { p: 0 };
        tl.set(light, { opacity: 1 }, at);
        tl.to(o, {
          p: 1, duration: dur, ease: EASINGS.powerInOut,
          onUpdate: () => {
            const pt = arc.getPointAtLength(o.p * len);
            gsap.set(light, { x: pt.x, y: pt.y });
          },
        }, at);
        tl.to(light, { opacity: 0, duration: DURATIONS.micro }, at + dur);
      };

      const tl = gsap.timeline({
        defaults: { ease: EASINGS.out },
        scrollTrigger: { trigger: root.querySelector('.pim-frame'), start: 'top 72%', once: true },
      });
      tl.to(worldDots, { opacity: 1, duration: DURATIONS.full, ease: EASINGS.out }, 0)
        .to(outline, { strokeDashoffset: 0, duration: DURATIONS.full, ease: EASINGS.inOut }, 0.2)
        .to(outline, { fillOpacity: 1, duration: DURATIONS.long, ease: EASINGS.out }, 0.9)
        .to([indiaDots, islands], { opacity: 1, duration: DURATIONS.long, ease: EASINGS.out }, 0.7)
        .to(origin, { opacity: 1, duration: DURATIONS.short, ease: EASINGS.out }, 1.0);
      dArcs.forEach((arc, i) => {
        const at = 1.2 + i * 0.07;
        tl.to(arc, { strokeDashoffset: 0, duration: DURATIONS.medium, ease: EASINGS.powerInOut }, at);
        tl.to(ends[i], { opacity: 1, duration: DURATIONS.short }, at + DURATIONS.medium);
        if (lights[i]) ride(arc, lights[i], at + DURATIONS.medium, DURATIONS.long, tl);
      });
      const wStart = 1.2 + dArcs.length * 0.07 + 0.5;
      wArcs.forEach((arc, i) => {
        const at = wStart + i * 0.14;
        const k = dArcs.length + i;
        tl.to(arc, { strokeDashoffset: 0, duration: DURATIONS.full, ease: EASINGS.inOut }, at);
        tl.to(ends[k], { opacity: 1, duration: DURATIONS.short }, at + DURATIONS.full);
        if (lights[k]) ride(arc, lights[k], at + DURATIONS.full, DURATIONS.full, tl);
      });

      return () => {
        tl.scrollTrigger?.kill();
        tl.kill();
        gsap.set([worldDots, indiaDots, islands, outline, ...dArcs, ...wArcs, ...ends, ...lights, ...origin], { clearProps: 'all' });
      };
    });
    return () => mm.revert();
  }, { scope: sectionRef });

  return (
    <section ref={sectionRef} className="pim" aria-labelledby="map-heading" data-hl={hl ?? undefined}>
      <style>{CSS}</style>
      <div className="pim-inner">
        <div className="pim-head">
          <div>
            <div className="pim-label">Pan Bharat</div>
            <h2 id="map-heading" ref={headingRef} className="pim-h2">The catalogue is only where we begin.</h2>
            {/* COPY: drafted from verified facts (§5.10; custom development from sample/drawing/photo; Pan Bharat delivery network) — needs client approval */}
            <p className="pim-lead">
              <Highlight keywords={['Pan Bharat delivery network']}>
                {`Alok Plastics makes far more than the parts you see listed. We develop and supply parts to your sample or drawing, for equipment across many industries, and dispatch from ${site.contact.city} through our Pan Bharat delivery network.`}
              </Highlight>
            </p>
          </div>
          <ul className="pim-legend" aria-label="Map key. Choose a row to highlight that layer.">
            {LEGEND.map(({ layer, text }) => (
              <li key={layer}>
                <button
                  type="button"
                  aria-pressed={pin === layer}
                  onClick={() => setPin(p => (p === layer ? null : layer))}
                  onFocus={() => setPeek(layer)}
                  onBlur={() => setPeek(null)}
                  onPointerEnter={() => setPeek(layer)}
                  onPointerLeave={() => setPeek(null)}
                >
                  <svg width="22" height="22" viewBox="0 0 22 22" aria-hidden="true">
                    {layer === 'origin' && (
                      <>
                        <circle cx="11" cy="11" r="9" fill="none" stroke="var(--map-origin)" strokeWidth="1" opacity="0.5" />
                        <circle cx="11" cy="11" r="5" fill="var(--map-origin)" />
                      </>
                    )}
                    {layer === 'domestic' && (
                      <>
                        <defs>
                          <linearGradient id="pim-sw" gradientUnits="userSpaceOnUse" x1="2" y1="17" x2="20" y2="6">
                            <stop offset="0%" style={{ stopColor: 'var(--map-arc-hot)' }} />
                            <stop offset="100%" style={{ stopColor: 'var(--map-arc-domestic)' }} />
                          </linearGradient>
                        </defs>
                        <path d="M2 17Q11 2 20 6" fill="none" stroke="url(#pim-sw)" strokeWidth="1.8" />
                      </>
                    )}
                    {layer === 'world' && <path d="M2 17Q11 2 20 6" fill="none" stroke="var(--map-arc-world)" strokeOpacity="0.9" strokeWidth="1.5" />}
                  </svg>
                  <span>{text}</span>
                </button>
              </li>
            ))}
          </ul>
        </div>

        <figure style={{ margin: 0 }}>
          <div className="pim-frame">
            <div className="pim-stage">
            <svg
              className="pim-svg"
              viewBox={`${VB.x} ${VB.y} ${VB.w} ${VB.h}`}
              fill="none"
              role="img"
              aria-label="Dot-matrix world map, colour-coded by layer: India in steel blue, Chandigarh as the amber origin of the Pan Bharat delivery network, arcs cooling from amber into burgundy for that network today, each ending on a small part pictogram, and lighter steel-grey arcs that are illustrative and show ambition, not delivery destinations."
            >
              <defs>
                {/* soft inner glow: the landmass is a touch denser at its border than at its core */}
                {/* each domestic arc cools from resin amber at the origin into burgundy at its badge */}
                {domestic.map((a, i) => (
                  <linearGradient key={`g${i}`} id={`pim-ga${i}`} gradientUnits="userSpaceOnUse" x1={ORIGIN.x} y1={ORIGIN.y} x2={a.p.x} y2={a.p.y}>
                    <stop offset="0%" style={{ stopColor: 'var(--map-arc-hot)' }} />
                    <stop offset="100%" style={{ stopColor: 'var(--map-arc-domestic)' }} />
                  </linearGradient>
                ))}
                <radialGradient id="pim-heat" cx="50%" cy="50%" r="50%">
                  <stop offset="0%" style={{ stopColor: 'var(--map-origin)', stopOpacity: 0.32 }} />
                  <stop offset="100%" style={{ stopColor: 'var(--map-origin)', stopOpacity: 0 }} />
                </radialGradient>
                <radialGradient id="pim-wash" cx="50%" cy="50%" r="62%">
                  <stop offset="0%" style={{ stopColor: 'var(--map-land)', stopOpacity: 0.07 }} />
                  <stop offset="70%" style={{ stopColor: 'var(--map-land)', stopOpacity: 0.14 }} />
                  <stop offset="100%" style={{ stopColor: 'var(--map-land)', stopOpacity: 0.26 }} />
                </radialGradient>
              </defs>
              {/* faint graticule, behind everything */}
              <path d={GRATICULE} stroke="var(--grey-metal)" strokeOpacity="0.1" strokeWidth="0.6" />
              {/* world backdrop: muted sand dots */}
              <path className="pim-world-dots" d={WORLD_DOTS} stroke="var(--map-world)" strokeOpacity="0.8" strokeWidth="2.6" strokeLinecap="round" strokeDasharray={`0 ${STEP_WORLD_U}`} />
              {/* India: Government of India depiction, enlarged in front of the world layer */}
              <g transform={IND_T}>
              <path className="pim-outline" d={INDIA_OUTLINE} pathLength={1} fill="url(#pim-wash)" stroke="var(--map-land)" strokeWidth={1.4 / INDIA_SCALE} strokeLinejoin="round" />
              <path className="pim-islands" d={INDIA_ISLANDS} fill="var(--map-land-alt)" fillOpacity="0.8" stroke="var(--map-land)" strokeWidth={0.5 / INDIA_SCALE} strokeLinejoin="round" />
              <path className="pim-india-dots" d={INDIA_DOTS} stroke="var(--map-land)" strokeOpacity="0.8" strokeWidth={1.5 / INDIA_SCALE} strokeLinecap="round" strokeDasharray={`0 ${STEP_INDIA_U}`} />
              </g>

              {/* arcs: dense inside India, longer and lighter across the world. DOM order matters to the
                  timeline: domestic arcs / ends / lights come first, then world, so the indexes line up. */}
              <g className="pim-g pim-g-domestic" {...hover('domestic')}>
                {domestic.map((a, i) => (
                  <g key={`d${i}`}>
                    <path className="pim-arc-d" d={a.d} pathLength={1} stroke={`url(#pim-ga${i})`} strokeOpacity="0.9" strokeWidth="1.3" strokeLinecap="round" />
                    <path className="pim-hit" d={a.d}><title>Pan Bharat delivery network, today</title></path>
                  </g>
                ))}
                {domestic.map((a, i) => (
                  <g key={`e${i}`} visibility={inFrame(a.p) ? 'visible' : 'hidden'} className="pim-end">
                    <circle cx={a.p.x} cy={a.p.y} r={BADGE_R} fill="var(--surface)" stroke="var(--map-arc-domestic)" strokeWidth="1.2" />
                    <g transform={`translate(${round(a.p.x - GLYPH / 2)} ${round(a.p.y - GLYPH / 2)}) scale(${GLYPH / 48})`} fill="none" stroke="var(--burgundy)" strokeWidth="1.1" strokeLinecap="square" strokeLinejoin="miter">
                      {pictogramPaths[a.glyph].paths.map((d, k) => <path key={k} d={d} vectorEffect="non-scaling-stroke" />)}
                    </g>
                  </g>
                ))}
              </g>
              <g className="pim-g pim-g-world" {...hover('world')}>
                {world.map((a, i) => (
                  <g key={`w${i}`}>
                    <path className="pim-arc-w" d={a.d} pathLength={1} stroke="var(--map-arc-world)" strokeOpacity="0.9" strokeWidth="1.3" strokeLinecap="round" />
                    <path className="pim-hit" d={a.d}><title>The ambition: a globally recognised Indian manufacturing brand</title></path>
                  </g>
                ))}
                {world.map((a, i) => (
                  <circle key={`e${i}`} visibility={inFrame(a.p) ? 'visible' : 'hidden'} className="pim-end" cx={a.p.x} cy={a.p.y} r={3.4} fill="var(--surface)" stroke="var(--map-node)" strokeWidth="1.3" />
                ))}
              </g>
              {[...domestic, ...world].map((_, i) => (
                <circle key={`l${i}`} className="pim-light" r="2.8" fill={i < domestic.length ? 'var(--map-arc-hot)' : 'var(--map-node)'} />
              ))}

              {/* origin: Chandigarh */}
              <g className="pim-origin">
                <circle cx={ORIGIN.x} cy={ORIGIN.y} r="64" fill="url(#pim-heat)" />
                <circle className="pim-ring" cx={ORIGIN.x} cy={ORIGIN.y} r="24" stroke="var(--map-origin)" strokeWidth="1.2" />
                <circle className="pim-ring b" cx={ORIGIN.x} cy={ORIGIN.y} r="24" stroke="var(--map-origin)" strokeWidth="1.2" />
                <circle className="pim-dot" cx={ORIGIN.x} cy={ORIGIN.y} r="5" fill="var(--map-origin)" stroke="var(--surface)" strokeWidth="1.5" />
              </g>
            </svg>
            </div>
            <span className="pim-reg tl" aria-hidden="true" /><span className="pim-reg tr" aria-hidden="true" />
            <span className="pim-reg bl" aria-hidden="true" /><span className="pim-reg br" aria-hidden="true" />
          </div>

          <figcaption className="pim-foot">
            <p className="pim-note">Illustrative. Arcs show direction of travel, not delivery destinations.</p>
          </figcaption>
        </figure>

        {/* Beyond the catalogue: custom parts, many industries, repeat orders */}
        <div className="pim-bey">
          <div>
            <h3 className="pim-bey-h">More made here than any catalogue shows.</h3>
            <p className="pim-bey-sub">The catalogue is where most buyers begin. If your part is not listed, it may still be one we can make.</p>
          </div>
          <div>
            <ul className="pim-bey-cols">
              <li className="pim-bey-col">
                <span className="pim-bey-k">Made to your sample</span>
                <p className="pim-bey-t">Bring a sample, drawing or photo.</p>
                <p className="pim-bey-p">We develop the part and supply it, from mould development onward.</p>
              </li>
              <li className="pim-bey-col">
                <span className="pim-bey-k">Many industries</span>
                <p className="pim-bey-t">Not just coolers and freezers.</p>
                <p className="pim-bey-p">Parts for the industries we serve, wherever a plastic part has a job to do.</p>
              </li>
              <li className="pim-bey-col">
                <span className="pim-bey-k">Repeat orders</span>
                <p className="pim-bey-t">Ordered once, ordered again.</p>
                <p className="pim-bey-p">Buyers across India come back with the next order, and we dispatch it the same way.</p>
              </li>
            </ul>
            <div className="pim-bey-cta">
              <Link href="/enquiry/" className="pim-go">Send a sample or drawing <ArrowUpRight size={18} weight="light" aria-hidden="true" /></Link>
              <Link href="/industries/" className="pim-go">See the industries we serve <ArrowUpRight size={18} weight="light" aria-hidden="true" /></Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
